#!/bin/bash
set -euo pipefail

# Deploy discovery-only bootstrap nodes with Docker.
#
# Usage:
#   ./deploy/docker-bootstrap.sh setup [COUNT]   Generate identities + compose file
#   ./deploy/docker-bootstrap.sh up              Start bootstrap nodes
#   ./deploy/docker-bootstrap.sh status          Show peer info
#   ./deploy/docker-bootstrap.sh down            Stop bootstrap nodes
#   ./deploy/docker-bootstrap.sh clean           Remove all data and generated files
#
# Default: 3 bootstrap nodes on ports 4001-4003.

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
DATA_DIR="$ROOT_DIR/.bootstrap"
COMPOSE_FILE="$DATA_DIR/docker-compose.yml"
IMAGE_NAME="lattice-node"
DEFAULT_COUNT=3
BASE_PORT=4001

usage() {
    echo "Usage: $0 <command> [options]"
    echo ""
    echo "Commands:"
    echo "  setup [N]   Build image, generate N identities, write docker-compose.yml (default: 3)"
    echo "  up          Start all bootstrap nodes"
    echo "  status      Show public keys and peer counts"
    echo "  down        Stop all bootstrap nodes"
    echo "  clean       Remove all data volumes and generated files"
    echo ""
    echo "Example:"
    echo "  $0 setup 5          # 5 bootstrap nodes"
    echo "  $0 up               # start them"
    echo "  $0 status           # check connections"
    exit 1
}

build_image() {
    echo "Building Docker image..."
    docker build -t "$IMAGE_NAME" "$ROOT_DIR" --quiet
    echo "Image built: $IMAGE_NAME"
}

generate_identity() {
    local node_num=$1
    local node_dir="$DATA_DIR/seed-${node_num}"
    mkdir -p "$node_dir"

    if [ -f "$node_dir/identity.json" ]; then
        # Already exists, just read the public key
        local pubkey
        pubkey=$(docker run --rm -v "$node_dir:/home/lattice/.lattice" "$IMAGE_NAME" identity --data-dir /home/lattice/.lattice)
        echo "$pubkey"
        return
    fi

    local pubkey
    pubkey=$(docker run --rm -v "$node_dir:/home/lattice/.lattice" "$IMAGE_NAME" identity --data-dir /home/lattice/.lattice)
    echo "$pubkey"
}

write_compose() {
    local count=$1
    shift
    local pubkeys=("$@")

    cat > "$COMPOSE_FILE" <<'HEADER'
# Auto-generated by docker-bootstrap.sh
# Discovery-only bootstrap nodes for Lattice network
services:
HEADER

    for i in $(seq 1 "$count"); do
        local port=$((BASE_PORT + i - 1))
        local service_name="seed-${i}"

        # Build --peer flags for all OTHER nodes
        local peer_flags=""
        for j in $(seq 1 "$count"); do
            if [ "$j" -ne "$i" ]; then
                peer_flags="${peer_flags}      - \"--peer=${pubkeys[$((j-1))]}@seed-${j}:4001\"\n"
            fi
        done

        cat >> "$COMPOSE_FILE" <<EOF
  ${service_name}:
    image: ${IMAGE_NAME}
    container_name: lattice-${service_name}
    ports:
      - "${port}:4001"
    volumes:
      - ${SCRIPT_DIR}/../.bootstrap/seed-${i}:/home/lattice/.lattice
    networks:
      - lattice-bootstrap
    command:
      - "node"
      - "--discovery-only"
      - "--port=4001"
      - "--data-dir=/home/lattice/.lattice"
$(echo -e "$peer_flags")    restart: unless-stopped

EOF
    done

    cat >> "$COMPOSE_FILE" <<'FOOTER'
networks:
  lattice-bootstrap:
    driver: bridge
FOOTER

    echo "Wrote $COMPOSE_FILE"
}

cmd_setup() {
    local count=${1:-$DEFAULT_COUNT}
    echo "Setting up $count bootstrap nodes..."
    echo ""

    mkdir -p "$DATA_DIR"
    build_image

    # Generate identities
    local pubkeys=()
    for i in $(seq 1 "$count"); do
        echo -n "  Generating identity for seed-${i}... "
        local pubkey
        pubkey=$(generate_identity "$i")
        pubkeys+=("$pubkey")
        echo "${pubkey:0:32}..."
    done
    echo ""

    # Write compose file
    write_compose "$count" "${pubkeys[@]}"

    echo ""
    echo "Bootstrap nodes ready. Next steps:"
    echo "  $0 up        # start all nodes"
    echo "  $0 status    # check peer connections"
    echo ""
    echo "To add these as hardcoded bootstrap peers, update BootstrapPeers.swift with:"
    echo ""
    for i in $(seq 1 "$count"); do
        local port=$((BASE_PORT + i - 1))
        echo "  PeerEndpoint(publicKey: \"${pubkeys[$((i-1))]}\", host: \"<external-ip>\", port: ${port}),"
    done
}

cmd_up() {
    if [ ! -f "$COMPOSE_FILE" ]; then
        echo "No compose file found. Run '$0 setup' first."
        exit 1
    fi
    docker compose -f "$COMPOSE_FILE" up -d
    echo ""
    echo "Bootstrap nodes started. Run '$0 status' to check."
}

cmd_status() {
    if [ ! -f "$COMPOSE_FILE" ]; then
        echo "No compose file found. Run '$0 setup' first."
        exit 1
    fi

    echo "Bootstrap node status:"
    echo ""

    for dir in "$DATA_DIR"/seed-*; do
        [ -d "$dir" ] || continue
        local name=$(basename "$dir")
        local identity="$dir/identity.json"
        if [ -f "$identity" ]; then
            local pubkey
            pubkey=$(python3 -c "import json; print(json.load(open('$identity'))['publicKey'])" 2>/dev/null || echo "unknown")
            local health_file="$dir/health"
            local status="stopped"
            if [ -f "$health_file" ]; then
                status=$(grep -o 'status: [A-Z]*' "$health_file" 2>/dev/null || echo "status: unknown")
                local peers=$(grep -o 'peers: [0-9]*' "$health_file" 2>/dev/null || echo "peers: ?")
                status="$status, $peers"
            fi
            echo "  $name: ${pubkey:0:32}... ($status)"
        fi
    done

    echo ""
    docker compose -f "$COMPOSE_FILE" ps 2>/dev/null || true
}

cmd_down() {
    if [ ! -f "$COMPOSE_FILE" ]; then
        echo "No compose file found."
        exit 1
    fi
    docker compose -f "$COMPOSE_FILE" down
}

cmd_clean() {
    cmd_down 2>/dev/null || true
    rm -rf "$DATA_DIR"
    echo "Cleaned up bootstrap data."
}

case "${1:-}" in
    setup)  cmd_setup "${2:-}" ;;
    up)     cmd_up ;;
    status) cmd_status ;;
    down)   cmd_down ;;
    clean)  cmd_clean ;;
    *)      usage ;;
esac
